apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "chart.selectorLabels" . | nindent 6 }}
  ports:
  - name: port
    protocol: TCP
    port: 80
    targetPort: http

