name: 'custom-action'
description: 'testing custom docker-image gh action'
inputs:
  values:
    description: 'values for the chart'
    required: true
  set:
    description: 'set for the chart'
    required: true
outputs:
  helm-template:
    description: 'Helm template output'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.values }}
    - ${{ inputs.set }}
